---
title: "Progress Memo 2"
subtitle: |
  | Final Project 
  | Data Science 1 with R (STAT 301-1)
author: "Meera Trivedi"

format:
  html:
    toc: true
    embed-resources: true
    
execute:
  echo: false
  warning: false

from: markdown+emoji 
---

::: {.callout-tip icon="false"}
## Github Repo Link

[My GitHub Repo](https://github.com/stat301-1-2023-fall/final-project-1-meeratrivedi.git)
:::

## Data and Packages

```{r}
#| message: false

library(tidyverse)

lines <- read_csv("data/friends.csv")
info <- read_csv("data/friends_info.csv")
emotions <- read_csv("data/friends_emotions.csv")
```

## Investigating the Data

explanation

```{r}
glimpse(lines)
```

```{r}
glimpse(info)
```

```{r}
glimpse(emotions)
```

## Data Cleaning

### Joining Datasets

explanation

```{r}
lines_emotions <- lines |> 
  filter(speaker != "Scene Directions") |> 
  left_join(emotions)
```

```{r}
linesinfo <- 
lines |> 
  full_join(info)
```


### Subsetting Data
```{r}
monica <- lines |> 
  filter(speaker == "Monica Geller") 
```


```{r}
maincharacters <- lines |> 
  filter(speaker %in% c("Monica Geller", 
                        "Ross Geller", 
                        "Rachel Green", 
                        "Phoebe Buffay", 
                        "Joey Tribbiani", 
                        "Chandler Bing"))
```

```{r}
guestcharacters <- lines |> 
  filter(!speaker %in% c("Monica Geller", 
                         "Ross Geller", 
                         "Rachel Green", 
                         "Phoebe Buffay", 
                         "Joey Tribbiani", 
                         "Chandler Bing", 
                         "Scene Directions", 
                         "#ALL#")) |> 
  filter(!is.na(speaker))
```

```{r}
topguestcharacters <- guestcharacters |> 
  group_by(speaker) |> 
  count(speaker) |> 
  filter(n > 10) |> 
  arrange(desc(n)) |> 
  rename(num_lines = n)
```

```{r}
writers <- info |> 
  count(written_by) |>
  filter(n > 1) |> 
  arrange(desc(n)) |> 
  rename(episodes_written = n) |> 
  slice_max(episodes_written, n = 10)
```

```{r}
topguestlines <- lines |> 
  filter(speaker %in% c("Mike Hannigan", 
                        "Richard Burke", 
                        "Janice Litman Goralnik", 
                        "Carol Willick", 
                        "Charlie Wheeler", 
                        "Judy Geller", 
                        "Frank Buffay Jr.", 
                        "Emily Waltham", 
                        "Jack Geller", 
                        "Tag Jones")) |> 
  mutate(speaker = factor(speaker, 
                          #order of levels
                          levels = c("Mike Hannigan", 
                                     "Richard Burke", 
                                     "Janice Litman Goralnik", 
                                     "Carol Willick", 
                                     "Charlie Wheeler", 
                                     "Judy Geller", 
                                     "Frank Buffay Jr.", 
                                     "Emily Waltham", 
                                     "Jack Geller", 
                                     "Tag Jones")))
```



## Summary Statistics

explanation

```{r}
info |> 
  summarize(mean = mean(imdb_rating), 
            .by = season) |>
  knitr::kable()
```


```{r}
info |> 
  summarize(mean = mean(us_views_millions), 
            .by = season) |> 
  knitr::kable()
```

## Univariate Analyses

explanation

```{r}
#main characters line count
labels <- maincharacters |> 
  count(speaker)

ggplot(maincharacters, aes(x = speaker, fill = speaker)) +
  geom_bar(show.legend = FALSE) + 
  geom_text(data = labels, 
            aes(y = n, label = n), 
            nudge_y = -50, vjust = "top") + 
  scale_fill_manual(name = NULL, 
                    values = c("#FFBC00", "#00B4EA", "#FF181E", "#FFBC00", "#00B4EA", "#FF181E"))+ 
  theme_minimal()
```
```{r}
monica |> 
  group_by(season) |> 
  count(speaker) |> 
  ggplot(aes(x = season, y = n)) + 
  geom_point(size = 3)+
  geom_line()+
  scale_x_continuous(breaks = seq(0, 10, 1))
```
```{r}
topguestlines |> 
  ggplot(aes(x = speaker, fill = speaker))+
  geom_bar(show.legend = FALSE)+
  scale_x_discrete(name = NULL, 
                   labels = c("Mike \n Hannigan", 
                              "Richard \n Burke", 
                              "Janice \n Litman \n Goralnik", 
                              "Carol \n Willick", 
                              "Charlie \n Wheeler", 
                              "Judy \n Geller", 
                              "Frank \n Buffay \n Jr.", 
                              "Emily \n Waltham", 
                              "Jack \n Geller", 
                              "Tag \n Jones")) +
  theme_minimal()
```
```{r}
label_numbers <- lines_emotions |> 
  count(emotion) |> 
  filter(!is.na(emotion))

lines_emotions |> 
  count(emotion) |> 
  filter(!is.na(emotion)) |> 
  ggplot(aes(x = emotion, y = n, fill = emotion)) +
  geom_col(show.legend = FALSE)+
  geom_text(data = label_numbers, 
            aes(y = n, label = n), 
            color = "white",
            size = 5,
            nudge_y = -25, vjust = "top")+
  scale_fill_manual(name = NULL, 
                    values = c("mediumturquoise", "darkturquoise", "turquoise", "mediumturquoise", "darkturquoise", "turquoise", "mediumturquoise"))+
  theme_minimal()
```

## Multivariate Analyses

explanation

```{r}
#main character lines throughout the seasons
maincharacters |> 
  group_by(season) |> 
  count(speaker) |> 
  ggplot(aes(x = season, y = n, color = speaker))+
  geom_point(size = 3, show.legend = FALSE)+
  geom_line(show.legend = FALSE)+
  scale_x_continuous(breaks = seq(0, 10, 1))+
  facet_wrap(~speaker)
```
```{r}
ggplot(data = info, aes(us_views_millions, imdb_rating))+
  geom_jitter(alpha = 0.75)
```

## Summary of Progress

explanation

